### ISSUE TITLE
原版绕过大陆IP的PAC有点问题,访问网站速度响应非常慢

### ISSUE THREAD

**Issue by HellAction** [Azure99/ShadowSocksRCsM#2]
https://raw.githubusercontent.com/shadowsocks-r/breakwa11.github.io/master/ssr/ss_white.pac
换成以前的pac可以流畅访问,看看是否可以替换下
好像是改了dns解析方式,还有ipv6 dns的解析的支持导致的,不知道替换后有啥其他影响

**Comment by Azure99** [comment]
你这个PAC是绕过大陆常见域名的，不是绕过大陆IP，请检查下
另外推荐用绕过大陆常见域名

**Comment by HellAction** [comment]
嗯嗯,感谢科普~看了下确实是绕过大陆常见域名的PAC;
现在更新了下绕过大陆IP的PAC已经可以正常使用了.
线路是自己搭建的,流量不慌,毕竟国内网络直连大部分海外站点速度都太慢了,比如github,这个PAC对我来说最省心~
